Modules/User/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth','permission']], function () {
Route::resource('users', 'UserController');
});

Modules/User/Http/Controllers/UserController.php
<?php

namespace Modules\User\Http\Controllers;

use Illuminate\Routing\Controller;
use App\User;
use Illuminate\Support\Facades\Hash;
use Modules\User\Http\Requests\StoreUserRequest;
use Modules\User\Http\Requests\UpdateUserRequest;
use Spatie\Permission\Models\Role;
class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:view.user', ['only'=>'index']);
        $this->middleware('permission:create.user', ['only'=>'create']);
        $this->middleware('permission:edit.user', ['only'=>'edit']);
        $this->middleware('permission:delete.user', ['only'=>'destroy']);
    }

    public function index()
    {
        $users = User::latest()->paginate(10);
        return view('user::index', compact('users'));
    }

    public function create(User $user)
    {
        $role = Role::get();
        return view('user::create', [
            'user' => $user,
            'roles' => $role,
        ]);
    }

    public function store(User $user, StoreUserRequest $request)
    {  
        $user->syncRoles($request->get('role'));
        $user->create(array_merge($request->validated(), [
            'password' => Hash::make('password'),
        ]));
        return redirect()->route('users.index')->withSuccess(__('User created successfully.'));
    }


    public function edit(User $user)
    {
        return view('user::edit', [
            'user' => $user,
            'userRole' => $user->roles->pluck('name')->toArray(),
            'roles' => Role::latest()->get()
        ]);
    }


    public function update(UpdateUserRequest $request, User $user)
    {
        $user->update($request->validated());
        $user->syncRoles($request->get('role'));
        return redirect()->route('users.index')->withSuccess(__('User updated successfully.'));
    }

    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index')
            ->withSuccess(__('User deleted successfully.'));
    }
}

Modules/User/Resources/views/_form.blade.php
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" placeholder="name" class="form-control"
        value="{{ old('name') ?? $permission->name }}">
    @error('name')
        <div class="text-danger mt-2">{{ $message }}</div>
    @enderror
</div>

<button class="btn btn-primary">
    {{$submit}}
</button>

Modules/User/Resources/views/create.blade.php
@extends('employee::layouts.master')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Users</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Users </a></div>
                <div class="breadcrumb-item">Form</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Add Users</h2>
            <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Create New Users</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('users.store') }}" method="post">
                                @csrf

                                <div class="form-group">
                                    <label for="name">Nama</label>
                                    <input type="text" name="name" id="name" placeholder="name" class="form-control"
                                        value="{{ old('name') ?? $user->name }}">
                                    @error('name')
                                        <div class="text-danger mt-2">{{ $message }}</div>
                                    @enderror
                                </div>


                                <div class="form-group">
                                    <label for="nama">Email</label>
                                    <input type="email" name="email" id="email" placeholder="email" class="form-control"
                                        value="{{ old('email') ?? $user->email }}">
                                    @error('email')
                                        <div class="text-danger mt-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <label for="role" class="form-label">Role</label>
                                    <select class="form-control" name="role">
                                        <option value="">Select role</option>
                                        @foreach ($roles as $role)
                                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('role'))
                                        <span class="text-danger text-left">{{ $errors->first('role') }}</span>
                                    @endif
                                </div>
                                <button class="btn btn-primary mt-3">
                                    submit
                                </button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

Modules/User/Resources/views/edit.blade.php
@extends('employee::layouts.master')

@section('content')
<section class="section">
    <div class="section-header">
      <h1>User</h1>
      <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="#">User</a></div>
        <div class="breadcrumb-item">Form</div>
      </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Edit User</h2>
        <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Edit User - {{$user->name}}</h4>
                </div>
                <div class="card-body">
                  <form action="{{ route('users.update', $user) }}" method="post">
                    @csrf
                    @method('put')

                    <div class="form-group">
                        <label for="name">Nama</label>
                        <input type="text" name="name" id="name" placeholder="name" class="form-control"
                            value="{{ old('name') ?? $user->name }}">
                        @error('name')
                            <div class="text-danger mt-2">{{ $message }}</div>
                        @enderror
                    </div>
                    
                    
                    
                    <div class="form-group">
                        <label for="nama">Email</label>
                        <input type="email" name="email" id="email" placeholder="email" class="form-control"
                            value="{{ old('email') ?? $user->email }}">
                        @error('email')
                            <div class="text-danger mt-2">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="role" class="form-label">Role</label>
                        <select class="form-control" 
                            name="role">
                            <option value="">Select role</option>
                            @foreach($roles as $role)
                                <option value="{{ $role->id }}"
                                    {{ in_array($role->name, $userRole) 
                                        ? 'selected'
                                        : '' }}>{{ $role->name }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('role'))
                            <span class="text-danger text-left">{{ $errors->first('role') }}</span>
                        @endif
                    </div>
                    <button class="btn btn-primary mt-3">
                       update
                    </button>
                    
                </form>
                </div>
              </div>
            </div>
        </div>
    </div>
  </section>
@endsection

Modules/User/Resources/views/index.blade.php
@extends('permission::layouts.master')

@section('content')
@if (count($errors) > 0)
                <div class="row">
                    <div class="col-md-12 col-md-offset-1">
                      <div class="alert alert-danger alert-dismissible">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                          <h4><i class="icon fa fa-ban"></i> Error!</h4>
                          @foreach($errors->all() as $error)
                          {{ $error }} <br>
                          @endforeach      
                      </div>
                    </div>
                </div>
                @endif
  
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible text-center show fade">
                        <div class="alert-body">
                            <button class="close" data-dismiss="alert">
                                <span>&times;</span>
                            </button>
                            {{ session('success') }}
                        </div>
                    </div>
                @endif

<section class="section">
    <div class="section-header">
        <h1>Users</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Campaign</a></div>
            <div class="breadcrumb-item">Table</div>
        </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Users Table</h2>
        <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <div class="row">
            <div class="col-12">
                <x-alert />
                <div class="card">

                    <div class="card-header d-flex justify-content-between mt-2">
                        <div class="">
                            <a href="{{route('users.create')}}" class="btn btn-primary">Users<i
                                    class="fa fa-plus ml-2"></i></a>
                        </div>
                        <div class="card-header-form">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-btn">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>


                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Roles</th>
                                    <th>created at</th>
                                    <th>Action</th>
                                </tr>
                                @foreach ($users as $item)
                                    <tr>

                                        <td>{{ $users->count() * ($users->currentPage() - 1) + $loop->iteration }}
                                        </td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{$item->email}}</td>
                                        <td>
                                            @foreach($item->roles as $role)
                                                <span class="badge bg-primary text-light">{{ $role->name }}</span>
                                            @endforeach
                                        </td>
                                        <td>{{ $item->created_at->format('d M Y') }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip"
                                                    title="Edit" href="{{ route('users.edit', $item) }}"><i
                                                        class="fas fa-pencil-alt"></i></a>

                                                <form action="{{ route('users.destroy', $item) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <button class="btn btn-danger btn-action" data-toggle="tooltip"
                                                        title="Delete" onclick="confirm('are you sure want delete')"><i
                                                            class="fas fa-trash"></i></button>

                                                </form>
                                            </div>

                                        </td>
                                    </tr>
                                @endforeach

                            </table>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <nav class="d-inline-block">
                            <ul class="pagination mb-0">
                                {!! $users->links() !!}
                            </ul>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </div>


</section>
@endsection