Modules/Role/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth','permission']], function () {

Route::resource('roles', 'RoleController');
});

Modules/Role/Http/Controllers/RoleController.php
<?php

namespace Modules\Role\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;


class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:view.roles', ['only'=>'index']);
        $this->middleware('permission:create.roles', ['only'=>'create']);
        $this->middleware('permission:edit.roles', ['only'=>'edit']);
        $this->middleware('permission:delete.roles', ['only'=>'destroy']);
    }
   
    public function index(Request $request)
    {    $roles = Role::orderBy('id', 'DESC')->paginate(5);
        return view('role::index', compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }


    public function create(Role $roles)
    {
        $permissions = Permission::get();
        return view('role::create', compact('permissions','roles'));
    }

    public function store(Request $request)
    {
      //  return $request;
        $request->validate( [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->get('name')]);
        $role->syncPermissions($request->get('permission'));

        return redirect()->route('roles.index')
            ->with('success', 'Role created successfully');
    }


    public function edit(Role $role)
    {
        $role = $role;
        $rolePermissions = $role->permissions->pluck('name')->toArray();
        $permission = Permission::get();

        return view('role::edit', compact('role', 'rolePermissions', 'permission'));
    }

 
    public function update(Role $role, Request $request)
    {
        $request->validate( [
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role->update($request->only('name'));

        $role->syncPermissions($request->get('permission'));

        return redirect()->route('roles.index')
            ->with('success', 'Role updated successfully');
    }


    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('roles.index');
    }
}

Modules/Role/Resources/views/_form.blade.php
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" placeholder="name" class="form-control"
        value="{{ old('name') ?? $permission->name }}">
    @error('name')
        <div class="text-danger mt-2">{{ $message }}</div>
    @enderror
</div>

<button class="btn btn-primary">
    {{$submit}}
</button>

Modules/Role/Resources/views/create.blade.php
@extends('employee::layouts.master')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Roles</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Roles</a></div>
                <div class="breadcrumb-item">Form</div>
            </div>
        </div>
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="section-body">
            <h2 class="section-title">Add Roles</h2>
            <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <div class="row">

                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Create New Roles</h4>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{{ route('roles.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" name="name" id="name" placeholder="name" class="form-control"
                                        value="{{ old('name') ?? $roles->name }}">
                                    @error('name')
                                        <div class="text-danger mt-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="card-body">
                                    <table class="table table-responsive">
                                        <thead>
                                            <th scope="col" width="1%"><input type="checkbox" name="all_permission">
                                            </th>
                                            <th scope="col" width="20%">Permissions</th>
                                            <th scope="col" width="1%">Guard</th>
                                        </thead>
                                        @foreach ($permissions as $item)
                                            <tr>
                                                <td>
                                                    <input type="checkbox" name="permission[{{ $item->name }}]"
                                                        value="{{ old('all_permission') ?? $item->name }}"
                                                        class='permission'>
                                                </td>
                                                <td>
                                                    {{ $item->name }}
                                                </td>
                                                <td>
                                                    {{ $item->guard_name }}
                                                </td>
                                            </tr>
                                        @endforeach

                                    </table>
                                </div>


                                <button class="btn btn-primary">
                                    submit
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            $('[name="all_permission"]').on('click', function() {

                if ($(this).is(':checked')) {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', true);
                    });
                } else {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', false);
                    });
                }

            });
        });
    </script>
@endsection

Modules/Role/Resources/views/edit.blade.php
@extends('employee::layouts.master')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Role</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Role</a></div>
                <div class="breadcrumb-item">Form</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Edit Role</h2>
            <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Edit Role - {{ $role->name }}</h4>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{{ route('roles.update', $role) }}" enctype="multipart/form-data">
                                @csrf
                                @method('put')

                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" name="name" id="name" placeholder="name" class="form-control"
                                        value="{{ old('name') ?? $role->name }}">
                                    @error('name')
                                        <div class="text-danger mt-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <div class="card">
                                        <div class="card-header">
                                            Assign Permission
                                        </div>
                                        <div class="card-body">
                                            <table class="table table-responsive">
                                                <thead>
                                                    <th scope="col" width="1%"><input type="checkbox" name="all_permission">
                                                    </th>
                                                    <th scope="col" width="20%">Name</th>
                                                    <th scope="col" width="1%">Guard</th>
                                                </thead>
                                                @foreach ($permission as $item)

                                                    <tr>

                                                        <td>
                                                            <input type="checkbox" name="permission[{{ $item->name }}]"
                                                                value="{{ $item->name }}" class='permission'
                                                                {{ in_array($item->name, $rolePermissions) ? 'checked' : '' }}>
                                                        </td>
                                                        <td>
                                                            {{ $item->name }}
                                                        </td>
                                                        <td>
                                                            {{ $item->guard_name }}
                                                        </td>
                                                    </tr>
                                                @endforeach

                                            </table>
                                        </div>
                                    </div>


                                </div>

                                <button class="btn btn-primary">
                                    submit
                                </button>


                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            $('[name="all_permission"]').on('click', function() {

                if ($(this).is(':checked')) {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', true);
                    });
                } else {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', false);
                    });
                }

            });
        });
    </script>
@endsection

Modules/Role/Resources/views/index.blade.php
@extends('permission::layouts.master')

@section('content')
@if (count($errors) > 0)
                <div class="row">
                    <div class="col-md-12 col-md-offset-1">
                      <div class="alert alert-danger alert-dismissible">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                          <h4><i class="icon fa fa-ban"></i> Error!</h4>
                          @foreach($errors->all() as $error)
                          {{ $error }} <br>
                          @endforeach      
                      </div>
                    </div>
                </div>
                @endif
  
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible text-center show fade">
                        <div class="alert-body">
                            <button class="close" data-dismiss="alert">
                                <span>&times;</span>
                            </button>
                            {{ session('success') }}
                        </div>
                    </div>
                @endif

<section class="section">
    <div class="section-header">
        <h1>Roles</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">roles</a></div>
            <div class="breadcrumb-item">Table</div>
        </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Roles Table</h2>
        <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <div class="row">
            <div class="col-12">
                <x-alert />
                <div class="card">

                    <div class="card-header d-flex justify-content-between mt-2">
                        <div class="">
                            <a href="{{route('roles.create')}}" class="btn btn-primary">Roles <i
                                    class="fa fa-plus ml-2"></i></a>
                        </div>
                        

                        <div class="card-header-form">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-btn">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>


                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>No.</th>
                                    <th>Name</th>
                                    <th>Created</th>
                                    <th>Aksi</th>
                                </tr>
                                
                                @foreach ($roles as $item)
                                    @php
                                        $index =0;
                                    @endphp
                                    <tr>
                                      <td>{{$index+1}}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->created_at->format('d M Y') }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"
                                                    href="{{ route('roles.edit', $item->id) }}">Edit</a>
    
    
                                                <form action="{{ route('roles.destroy', $item->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
    
                                                    <button class="btn btn-danger btn-action" data-toggle="tooltip"
                                                        title="Delete"
                                                        onclick="confirm('are you sure want delete')">Delete</button>
    
                                                </form>
    
                                       
    
                                            </div>
                                        </td>
                                        <td>
    
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
    
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <nav class="d-inline-block">
                            <ul class="pagination mb-0">
                                {!! $roles->links() !!}
                            </ul>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </div>


</section>
@endsection

Modules/Role/Resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Udemy') }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <!-- Styles -->
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/components.css') }}" rel="stylesheet">
    <!-- Template CSS -->
    <!-- General JS Scripts -->

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="{{ asset('assets/js/stisla.js') }}"></script>


    <!-- Template JS File -->
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/js/custom.js') }}"></script>

   
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <!-- General CSS Files -->


</head>

<body>
    <div id="app">
     
            <div class="main-wrapper">
                <div class="navbar-bg"></div>


                @include('components.navbar')
                {{-- Sidebar --}}
                @include('components.sidebar')
                <!-- main Content -->

                <div class="main-content">
                    @yield('content')
                </div>
                {{-- footer --}}
                @include('components.footer')
            </div>
    
    </div>
</body>

</html>