Modules/Companie/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\Companie\Http\Controllers\CompanieController;
use Modules\Employee\Entities\Employee;
use Modules\Employee\Http\Controllers\EmployeeController;
Route::group(['middleware' => ['auth']], function () {
Route::resource('companie', 'CompanieController',['name'=>'company']);
    Route::get('print/{companie}', 'CompanieController@print')->name('employee.print');
});

Modules/Companie/Entities/Company.php
<?php

namespace Modules\Companie\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Employee\Entities\Employee;

class Company extends Model
{
  

    protected $guarded = [];
    public function employes(){
        return $this->hasMany(Employee::class, 'companies_id');
    }

}

Modules/Companie/Http/Controllers/CompanieController.php
<?php

namespace Modules\Companie\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Validator;
use Modules\Companie\Repositories\CompanieRepository;
use Modules\Companie\Entities\Company;
use Modules\Companie\Http\Requests\CompanyRequest;
use PDF;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Storage;

class CompanieController extends Controller
{

    public function __construct(CompanieRepository $companie)
    {
        $this->companie = $companie;
    
        $this->middleware('permission:view.company', ['only'=>'index']);
        $this->middleware('permission:create.company', ['only'=>'create']);
        $this->middleware('permission:edit.company', ['only'=>'edit']);
        $this->middleware('permission:delete.company', ['only'=>'destroy']);
    }


    public function index()
    {
       

        $companie = $this->companie->getCompanie();
        return view('companie::index', compact('companie'));
    }

    public function select2(Request $request)
    {
        

        $companie = $this->companie->getSelect2Data($request);
        return $companie;
    }


    public function show(Company $companie)
    {
        $employee = $companie->employes()->latest()->paginate(5);
        return view('companie::list', compact('employee', 'companie'));
    }

    public function print(Company $companie)
    {


        //  $employee = $companie->employes()->get();
        $employee = DB::table('employees')
            ->join('companies', 'companies.id', '=', 'employees.companies_id')
            ->select('employees.nama', 'employees.email', 'employees.created_at as since', 'companies.name as companies')->where('companies_id', $companie->id)
            ->get();
        $pdf = PDF::loadview('companie::export._pdf', ['employee' => $employee, 'companie' => $companie])->setOptions(['defaultFont' => 'sans-serif']);
        return $pdf->stream('laporan-pegawai-pdf');
    }

    public function create(Company $companie)
    {
       

        return view('companie::create', compact('companie', 'companie'));
    }


    public function store(CompanyRequest $request)
    {

        $this->companie->store($request);
        return redirect(route('companie.index'))->with('success', 'create employe succes!');
    }


    public function edit(Company $companie)
    {
        $companies = $this->companie->getCompanie();
        return view('companie::edit', compact('companie', 'companies'));
    }


    public function update(CompanyRequest $request, Company $companie)
    {
        $this->companie->update($request, $companie);
        return redirect(route('companie.index'))->with('success', 'update employe succes!');
    }


    public function destroy(Company $companie)
    {

        $this->companie->destroy($companie);
        return redirect(route('companie.index'))->with('success', 'delete emplye succes!');
    }


    // api


    public function getCompany()
    {
        $companie = $this->companie->getCompanie();
        return response()->json($companie);
    }

    public function getCompanyId(Company $companie)
    {
        return response()->json($companie);
    }

    public function storeCompany(CompanyRequest $request)
    {

        Company::create([
            'name' => $request->name,
            'website' => $request->website,
            'email' => $request->email,
            'logo' => $request->file('logo')->store('app/company'),
        ]);
        return response()->json([
            'success' => true,
            'message' => "sukses",

        ]);
    }


    public function updateCompany(CompanyRequest $request, Company $companie)
    {

        if ($request->logo) {
            Storage::delete($companie->logo);

            $logo = $request->file('logo')->store('app/company');
        } else {
            $logo = $companie->logo;
        }

        $companie->update([
            'name' => $request->name,
            'website' => $request->website,
            'email' => $request->email,
            'logo' => $logo
        ]);

        return response()->json([
            'success' => true,
            'message' => "sukses",
        ]);
    }

    public function deleteCompany(Company $companie)
    {

        $companie->delete();
        return response()->json([
            'success' => true,
            'message' => "sukses",
        ]);
    }
}

Modules/Companie/Resources/views/_form.blade.php
<div class="form-group">
    <label for="logo">logo</label>
    <input type="file" name="logo" id="logo" placeholder="logo" class="form-control"
        value="{{ old('logo') ?? $companie->logo }}">
    @error('logo')
        <div class="text-danger mt-2">{{ $message }}</div>
    @enderror
</div>
<div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" name="name" id="nama" placeholder="nama" class="form-control"
        value="{{ old('name') ?? $companie->name }}">
    @error('name')
        <div class="text-danger mt-2">{{ $message }}</div>
    @enderror
</div>
<div class="form-group">
    <label for="nama">Email</label>
    <input type="email" name="email" id="email" placeholder="email" class="form-control"    value="{{ old('email') ?? $companie->email }}">
    @error('email')
        <div class="text-danger mt-2">{{ $message }}</div>
    @enderror
</div>
<div class="form-group">
    <label for="website">website</label>
    <input type="text" name="website" id="website" placeholder="website" class="form-control"    value="{{ old('website') ?? $companie->website }}">
    @error('website')
        <div class="text-danger mt-2">{{ $message }}</div>
    @enderror
</div>




<button class="btn btn-primary">
    {{$submit}}
</button>

Modules/Companie/Resources/views/create.blade.php
@extends('employee::layouts.master')

@section('content')
<section class="section">
    <div class="section-header">
      <h1>Company</h1>
      <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="#">Companie</a></div>
        <div class="breadcrumb-item">Form</div>
      </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Add Company</h2>
        <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Create New Company</h4>
                </div>
                <div class="card-body">
                  <form method="post" action="{{route('companie.store')}}" enctype="multipart/form-data">
                    @csrf
                      @include('companie::_form',[
                        'submit'=>'Submit'
                      ])
                  </form>
                </div>
              </div>
            </div>
        </div>
    </div>
  </section>
@endsection

Modules/Companie/Resources/views/edit.blade.php
@extends('employee::layouts.master')

@section('content')
<section class="section">
    <div class="section-header">
      <h1>Company</h1>
      <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="#">Companie</a></div>
        <div class="breadcrumb-item">Form</div>
      </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Edit Company {{$companie->name}}</h2>
        <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4>Create New Company</h4>
                </div>
                <div class="card-body">
                  <form method="post" action="{{route('companie.update', $companie)}}" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    @if ($companie->logo)
                    <img src="{{asset('storage/'.$companie->logo)}}" width="500"/>
                    @else 
                     <img src="https://cdn.logo.com/hotlink-ok/logo-social.png" alt="" width="500">
                    @endif
                    
                      @include('companie::_form',[
                        'submit'=>'Update'
                      ])
                  </form>
                </div>
              </div>
            </div>
        </div>
    </div>
  </section>
@endsection

Modules/Companie/Resources/views/index.blade.php
@extends('employee::layouts.master')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Company</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Company</a></div>
                <div class="breadcrumb-item">Table</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Company Table</h2>
            <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <div class="row">
                <div class="col-12">
                    <x-alert />
                    <div class="card">

                        <div class="card-header d-flex justify-content-between mt-2">
                            <div class="">
                                <a href="{{ route('companie.create') }}" class="btn btn-primary">Company <i
                                        class="fa fa-plus ml-2"></i></a>
                            </div>

                            <div class="card-header-form">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>


                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tr>
                                        <th>
                                            <div class="custom-checkbox custom-control">
                                                <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                                                    class="custom-control-input" id="checkbox-all">
                                                <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                                            </div>
                                        </th>
                                        <th>#</th>
                                        <th>name</th>
                                        <th>email</th>
                                        <th>website</th>
                                        <th>logo</th>
                                        <th>created at</th>
                                        <th>Action</th>
                                    </tr>
                                    @foreach ($companie as $item)
                                        <tr>
                                            <td class="p-0 text-center">
                                                <div class="custom-checkbox custom-control">
                                                    <input type="checkbox" data-checkboxes="mygroup"
                                                        class="custom-control-input" id="checkbox-1">
                                                    <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                                                </div>
                                            </td>
                                            <td>{{ $companie->count() * ($companie->currentPage() - 1) + $loop->iteration }}
                                            </td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->website }}</td>
                                            <td>
                                                @if ($item->logo)
                                                    <img src="{{ asset('storage/' . $item->logo) }}" width="100" />
                                                @else
                                                    <img src="https://cdn.logo.com/hotlink-ok/logo-social.png" alt=""
                                                        width="100">
                                                @endif
                                            </td>


                                            <td>{{ $item->created_at->format('d M Y') }}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip"
                                                        title="Edit" href="{{ route('companie.edit', $item) }}"><i
                                                            class="fas fa-pencil-alt"></i></a>

                                                    <form action="{{ route('companie.destroy', $item) }}" method="post">
                                                        @csrf
                                                        @method('delete')

                                                        <button class="btn btn-danger btn-action" data-toggle="tooltip"
                                                            title="Delete" onclick="confirm('are you sure want delete')"><i
                                                                class="fas fa-trash"></i></button>

                                                    </form>
                                                    <a class="btn btn-primary btn-action ml-1" data-toggle="tooltip"
                                                        title="view company" href="{{ route('companie.show', $item) }}"><i
                                                            class="fas fa-eye"></i></a>
                                                </div>

                                            </td>
                                        </tr>
                                    @endforeach

                                </table>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <nav class="d-inline-block">
                                <ul class="pagination mb-0">
                                    {!! $companie->links() !!}
                                </ul>
                            </nav>
                        </div>

                    </div>
                </div>
            </div>
        </div>


    </section>
@endsection

Modules/Companie/Resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Udemy') }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <!-- Styles -->
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/components.css') }}" rel="stylesheet">
    <!-- Template CSS -->
    <!-- General JS Scripts -->

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="{{ asset('assets/js/stisla.js') }}"></script>


    <!-- Template JS File -->
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/js/custom.js') }}"></script>

   
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <!-- General CSS Files -->


</head>

<body>
    <div id="app">
   
            <div class="main-wrapper">
                <div class="navbar-bg"></div>


                @include('components.navbar')
                {{-- Sidebar --}}
                @include('components.sidebar')
                <!-- main Content -->

                <div class="main-content">
                    @yield('content')
                </div>
                {{-- footer --}}
                @include('components.footer')
            </div>

    </div>
</body>

</html>

Modules/Companie/Resources/views/list.blade.php
@extends('employee::layouts.master')

@section('content')


<section class="section">
    <div class="section-header">
        <h1>Company</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Company</a></div>
            <div class="breadcrumb-item">Table</div>
        </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">Company {{$companie->name}}</h2>
        <p class="section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <div class="row">
            <div class="col-12">
                <x-alert />
                <div class="card">

                    <div class="card-header d-flex justify-content-between mt-2">
                        <div class="">
                            <a href="{{route('employee.print', $companie)}}" class="btn btn-primary">PDF <i
                                    class="fa fa-print ml-2"></i></a>
                        </div>

                        <div class="card-header-form">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-btn">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>


                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>
                                        <div class="custom-checkbox custom-control">
                                            <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                                                class="custom-control-input" id="checkbox-all">
                                            <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                                        </div>
                                    </th>
                                    <th>#</th>
                                    <th>name</th>
                                    <th>email</th>
                                
                                  
                                    <th>created at</th>
                                    <th>Action</th>
                                </tr>
                                @foreach ($employee as $item)
                                    <tr>
                                        <td class="p-0 text-center">
                                            <div class="custom-checkbox custom-control">
                                                <input type="checkbox" data-checkboxes="mygroup"
                                                    class="custom-control-input" id="checkbox-1">
                                                <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                                            </div>
                                        </td>
                                        <td>{{ $employee->count() * ($employee->currentPage() - 1) + $loop->iteration }}
                                        </td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->email}}</td>
                                 

              
                                        <td>{{ $item->created_at->format('d M Y') }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip"
                                                    title="Edit" href="{{ route('employee.edit', $item) }}"><i
                                                        class="fas fa-pencil-alt"></i></a>

                                                <form action="{{ route('employee.destroy', $item) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <button class="btn btn-danger btn-action" data-toggle="tooltip"
                                                        title="Delete" onclick="confirm('are you sure want delete')"><i
                                                            class="fas fa-trash"></i></button>

                                                </form>
                                                <a class="btn btn-primary btn-action ml-1" data-toggle="tooltip"
                                                title="Edit" href="{{ route('employee.show', $item) }}"><i
                                                    class="fas fa-eye"></i></a>
                                            </div>

                                        </td>
                                    </tr>
                                @endforeach

                            </table>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <nav class="d-inline-block">
                            <ul class="pagination mb-0">
                                {!! $employee->links() !!}
                            </ul>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </div>


</section>
@endsection